# Generated by Django 5.1.6 on 2025-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrire',
            name='type_inscrition',
            field=models.CharField(choices=[('TPlein', 'Temps plein'), ('TPartiel', 'Temps partiel')], max_length=8),
        ),
    ]
